const jobs = [
    {
      id: 1,
      title: 'Frontend Developer',
      company: 'Google',
      location: 'California',
      description: 'Develop and maintain user-facing features for web applications.',
      salary: '$120K - $150K/year',
      techStack: ['React.js', 'JavaScript', 'HTML5', 'CSS3'],
      responsibilities: [
        'Build responsive web pages using React.js',
        'Optimize code for performance and scalability',
        'Work with designers to improve user experience',
      ],
      requirements: [
        '2+ years of experience with React.js',
        'Proficiency in HTML5, CSS3, and JavaScript',
        'Experience with RESTful APIs',
      ],
      benefits: ['Health insurance', 'Remote work', '401(k) matching'],
      jobType: 'Full-Time',
      experienceLevel: 'Mid-Level',
    },
    {
      id: 2,
      title: 'Backend Developer',
      company: 'Amazon',
      location: 'Seattle',
      description: 'Design and implement server-side logic and database solutions.',
      salary: '$130K - $160K/year',
      techStack: ['Node.js', 'Express.js', 'MongoDB', 'AWS'],
      responsibilities: [
        'Develop RESTful APIs and microservices',
        'Ensure data security and scalability',
        'Collaborate with frontend developers',
      ],
      requirements: [
        '3+ years of experience with Node.js',
        'Knowledge of cloud platforms (AWS, GCP)',
        'Strong understanding of database design',
      ],
      benefits: ['Stock options', 'Flexible hours', 'Health insurance'],
      jobType: 'Full-Time',
      experienceLevel: 'Senior',
    },
    {
      id: 3,
      title: 'Full Stack Developer',
      company: 'Microsoft',
      location: 'New York',
      description: 'Work on both front-end and back-end of web applications.',
      salary: '$140K - $170K/year',
      techStack: ['React.js', 'Node.js', 'GraphQL', 'PostgreSQL'],
      responsibilities: [
        'Develop and integrate APIs',
        'Ensure high performance and responsiveness',
        'Work closely with the design team',
      ],
      requirements: [
        '4+ years of full-stack development experience',
        'Experience with GraphQL and RESTful services',
        'Strong understanding of CI/CD pipelines',
      ],
      benefits: ['Parental leave', 'Gym membership', 'Stock options'],
      jobType: 'Full-Time',
      experienceLevel: 'Senior',
    },
    {
      id: 4,
      title: 'UI/UX Designer',
      company: 'Apple',
      location: 'San Francisco',
      description: 'Create user-friendly and visually appealing interfaces.',
      salary: '$100K - $130K/year',
      techStack: ['Figma', 'Sketch', 'Adobe XD'],
      responsibilities: [
        'Design mockups and wireframes',
        'Conduct user research and A/B testing',
        'Collaborate with developers to implement designs',
      ],
      requirements: [
        '2+ years of experience in UI/UX design',
        'Proficiency with design tools (Figma, Sketch)',
        'Strong portfolio of past design work',
      ],
      benefits: ['Education reimbursement', 'Health insurance', 'Remote work'],
      jobType: 'Part-Time',
      experienceLevel: 'Junior',
    },
    {
      id: 5,
      title: 'Mobile Developer',
      company: 'Samsung',
      location: 'Seoul',
      description: 'Build and maintain high-performance mobile applications.',
      salary: '$115K - $145K/year',
      techStack: ['Kotlin', 'Java', 'Swift', 'React Native'],
      responsibilities: [
        'Develop and release mobile applications',
        'Fix bugs and improve performance',
        'Collaborate with UI/UX team for better user experience',
      ],
      requirements: [
        '2+ years of experience in mobile development',
        'Experience with Kotlin, Java, and Swift',
        'Strong problem-solving skills',
      ],
      benefits: ['Health insurance', 'Performance bonus', 'Remote work'],
      jobType: 'Full-Time',
      experienceLevel: 'Mid-Level',
    },
    {
      id: 6,
      title: 'Data Scientist',
      company: 'Tesla',
      location: 'Palo Alto',
      description: 'Analyze data to improve production efficiency and quality.',
      salary: '$130K - $160K/year',
      techStack: ['Python', 'TensorFlow', 'SQL', 'Power BI'],
      responsibilities: [
        'Develop machine learning models',
        'Analyze large data sets',
        'Create data visualization reports',
      ],
      requirements: [
        '3+ years of experience as a Data Scientist',
        'Experience with Python and machine learning',
        'Strong analytical and mathematical skills',
      ],
      benefits: ['Company stock', 'Flexible work hours', 'Health insurance'],
      jobType: 'Full-Time',
      experienceLevel: 'Senior',
    },
    {
      id: 7,
      title: 'Cybersecurity Engineer',
      company: 'Cisco',
      location: 'San Francisco',
      description: 'Develop security protocols to protect company networks.',
      salary: '$140K - $170K/year',
      techStack: ['Firewalls', 'Penetration Testing', 'SIEM', 'Python'],
      responsibilities: [
        'Monitor and respond to security breaches',
        'Perform penetration tests',
        'Implement security improvements',
      ],
      requirements: [
        '3+ years of experience in cybersecurity',
        'Knowledge of firewalls and SIEM tools',
        'Security certifications (e.g., CISSP)',
      ],
      benefits: ['Stock options', '401(k) matching', 'Health insurance'],
      jobType: 'Full-Time',
      experienceLevel: 'Senior',
    },
    {
      id: 8,
      title: 'Game Developer',
      company: 'Sony',
      location: 'Tokyo',
      description: 'Develop and optimize game engines and graphics.',
      salary: '$110K - $140K/year',
      techStack: ['Unity', 'C++', 'Unreal Engine', 'OpenGL'],
      responsibilities: [
        'Design and implement game mechanics',
        'Optimize game performance',
        'Fix bugs and improve game features',
      ],
      requirements: [
        '2+ years of experience with Unity or Unreal Engine',
        'Proficiency in C++',
        'Strong understanding of game physics',
      ],
      benefits: ['Game discounts', 'Health insurance', 'Performance bonus'],
      jobType: 'Full-Time',
      experienceLevel: 'Mid-Level',
    },
    {
      id: 9,
      title: 'DevOps Engineer',
      company: 'IBM',
      location: 'Austin',
      description: 'Automate and improve development pipelines.',
      salary: '$120K - $150K/year',
      techStack: ['Docker', 'Kubernetes', 'Jenkins', 'AWS'],
      responsibilities: [
        'Set up CI/CD pipelines',
        'Manage cloud infrastructure',
        'Monitor and fix deployment issues',
      ],
      requirements: [
        '2+ years of experience in DevOps',
        'Experience with Kubernetes and Docker',
        'Strong scripting skills',
      ],
      benefits: ['Stock options', '401(k)', 'Flexible work hours'],
      jobType: 'Full-Time',
      experienceLevel: 'Mid-Level',
    }
  ];
  
  export default jobs;
  